# Generated by Django 5.2.6 on 2025-09-25 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0001_initial'),
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoequipo',
            name='ambiente_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='ambientes.ambiente'),
        ),
        migrations.AddField(
            model_name='movimientoequipo',
            name='ambiente_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='ambientes.ambiente'),
        ),
        migrations.AddField(
            model_name='movimientoequipo',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='movimientoequipo',
            name='usuario_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
